# -*- coding: utf-8 -*-
"""AI Text -to Image Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDKUlAvtxTtVVPnM89BiMlTyvp9e0K1K

AI Text-To Image Generator Using Stable Diffusion

Text-to-image generation is a process where an AI model creates images based on a text prompt given by the user.

Installing all tools required for this project.
"""

!pip install diffusers transformers accelerate --upgrade
!pip install safetensors

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

"""Logining into hugging face"""

from huggingface_hub import login
login("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")

"""Loading The Stable Diffusion Model"""

pipe = StableDiffusionPipeline.from_pretrained(
"runwayml/stable-diffusion-v1-5",
torch_dtype=torch.float16,
use_safetensors=True
)
pipe = pipe.to("cuda")

"""Giving Prompt"""

image = pipe(user_prompt).images[0]

# Display the generated image
plt.imshow(image)
plt.axis("off")
plt.title("Generated Image")
plt.show()

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

# Load the pre-trained model
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True
)
# Move the pipeline to the GPU
pipe = pipe.to("cuda")

# Define the user prompt
user_prompt = "a futuristic cityscape at night"

# Generate the image
image = pipe(user_prompt).images[0]

# Display the generated image
plt.imshow(image)
plt.axis("off")
plt.title("Generated Image")
plt.show()